// AI Service Types for Reflex

export type AIProvider = 'deepseek' | 'openai' | 'anthropic' | 'groq' | 'openrouter' | 'ollama' | 'qwen' | 'custom';

// ── Plan Mode Types ───────────────────────────────────────────────────────────
export interface PlanStep {
    id: number;
    description: string;
    status: 'pending' | 'in_progress' | 'completed' | 'failed' | 'skipped' | 'waiting_approval';
    command?: string;           // generated by Executor
    result?: string;            // success note from Assessor
    error?: string;             // failure note from Assessor
    requires_approval?: boolean; // 危险操作标记，执行前暂停等待用户确认
}

export interface PlanState {
    global_goal: string;
    scratchpad: string;  // accumulated useful info from Assessor
    plan: PlanStep[];
}

export interface AIConfig {
    provider: AIProvider;
    apiKey: string;
    baseUrl?: string; // For custom providers
    model?: string;
    privacyMode: boolean;
}

// Multi-provider profile — each saves a complete API endpoint config
export interface AIProviderProfile {
    id: string;             // uuid
    name: string;           // User-facing label, e.g. "DeepSeek V3", "My GPT-4o"
    provider: AIProvider;   // provider type for endpoint routing
    apiKey: string;
    baseUrl: string;        // auto-filled from AI_PROVIDER_CONFIGS or manual
    model: string;          // e.g. 'deepseek-chat', 'gpt-4o'
    models?: string[];      // optional list of models served by the same endpoint
    isDefault?: boolean;    // the one used when nothing is explicitly selected
}

export interface ChatMessage {
    role: 'system' | 'user' | 'assistant' | 'tool';
    content: string | null;
    reasoning_content?: string | null;
    tool_calls?: ToolCall[];
    tool_call_id?: string;
}

export interface AICompletionRequest {
    messages: ChatMessage[];
    stream?: boolean;
    temperature?: number;
    maxTokens?: number;
}

export interface AICompletionResponse {
    content: string;
    finishReason?: string;
}

// Function Calling types
export interface ToolDefinition {
    type: 'function';
    function: {
        name: string;
        description: string;
        parameters: object;
    };
}

export interface ToolCall {
    id: string;
    type: 'function';
    function: {
        name: string;
        arguments: string;
    };
}

export interface ToolCompletionResponse {
    content: string | null;
    reasoningContent?: string | null;  // DeepSeek reasoning_content
    toolCalls: ToolCall[] | null;
    finishReason: string;
    usage?: {
        promptTokens: number;
        completionTokens: number;
        totalTokens: number;
    };
    modelUsed?: string;
}

// Agent tools definition
export const AGENT_TOOLS: ToolDefinition[] = [
    {
        type: 'function',
        function: {
            name: 'execute_ssh_command',
            description: '在远程 Linux 服务器上通过 SSH 执行一条 Shell 命令，返回 stdout、stderr 和 exitCode。每次只能执行一条命令。',
            parameters: {
                type: 'object',
                properties: {
                    command: {
                        type: 'string',
                        description: '要执行的 Linux Shell 命令，例如 "df -h"、"systemctl status nginx"'
                    }
                },
                required: ['command']
            }
        }
    },
    {
        type: 'function',
        function: {
            name: 'read_file',
            description: '通过 SFTP 读取远程服务器上的文件内容。用于查看配置文件、源代码等。',
            parameters: {
                type: 'object',
                properties: {
                    path: {
                        type: 'string',
                        description: '文件的绝对路径，例如 "/etc/nginx/nginx.conf"'
                    }
                },
                required: ['path']
            }
        }
    },
    {
        type: 'function',
        function: {
            name: 'write_file',
            description: '通过 SFTP 将内容写入远程服务器上的文件。用于创建或修改配置文件、源代码等。',
            parameters: {
                type: 'object',
                properties: {
                    path: {
                        type: 'string',
                        description: '文件的绝对路径，例如 "/etc/nginx/conf.d/app.conf"'
                    },
                    content: {
                        type: 'string',
                        description: '要写入的文件内容'
                    }
                },
                required: ['path', 'content']
            }
        }
    },
    {
        type: 'function',
        function: {
            name: 'list_directory',
            description: '通过 SFTP 列出远程服务器上某个目录的文件和子目录列表。',
            parameters: {
                type: 'object',
                properties: {
                    path: {
                        type: 'string',
                        description: '目录的绝对路径，例如 "/var/www/html"'
                    }
                },
                required: ['path']
            }
        }
    }
];

// Default configurations for each provider
export const AI_PROVIDER_CONFIGS: Record<AIProvider, { baseUrl: string; defaultModel: string; displayName: string; hasFreeTier: boolean; note?: string }> = {
    groq: {
        baseUrl: 'https://api.groq.com/openai',
        defaultModel: 'llama-3.3-70b-versatile',
        displayName: 'Groq (免费)',
        hasFreeTier: true,
        note: '每分钟 30 请求免费'
    },
    openrouter: {
        baseUrl: 'https://openrouter.ai/api',
        defaultModel: 'meta-llama/llama-3.2-3b-instruct:free',
        displayName: 'OpenRouter (部分免费)',
        hasFreeTier: true,
        note: '部分模型免费'
    },
    ollama: {
        baseUrl: 'http://localhost:11434',
        defaultModel: 'llama3.2',
        displayName: 'Ollama (本地)',
        hasFreeTier: true,
        note: '需本地安装 Ollama'
    },
    deepseek: {
        baseUrl: 'https://api.deepseek.com',
        defaultModel: 'deepseek-chat',
        displayName: 'DeepSeek',
        hasFreeTier: false
    },
    openai: {
        baseUrl: 'https://api.openai.com',
        defaultModel: 'gpt-4o-mini',
        displayName: 'OpenAI',
        hasFreeTier: false
    },
    anthropic: {
        baseUrl: 'https://api.anthropic.com',
        defaultModel: 'claude-3-haiku-20240307',
        displayName: 'Anthropic',
        hasFreeTier: false
    },
    qwen: {
        baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        defaultModel: 'qwen-plus',
        displayName: '通义千问 (AliCloud)',
        hasFreeTier: true,
        note: '新用户有免费额度'
    },
    custom: {
        baseUrl: '',
        defaultModel: '',
        displayName: '自定义 (Custom)',
        hasFreeTier: false,
        note: '支持任何 OpenAI 兼容 API'
    }
};

// System prompts for different AI features
export const AI_SYSTEM_PROMPTS = {
    textToCommand: `你是一个 Linux/Unix 命令行专家。用户会用自然语言描述他们想做的事情，你需要将其转换为对应的 Shell 命令。

规则：
1. 只输出命令，不要解释
2. 如果需要多个命令，用 && 或 ; 连接
3. 使用常见的、跨平台兼容的命令
4. 如果涉及危险操作（如 rm -rf），请在命令前加注释警告

示例：
用户：查找当前目录下大于100M的文件
输出：find . -type f -size +100M -exec ls -lh {} \\;`,

    errorAnalysis: `你是一个专业的系统管理员和故障排查专家。用户会给你一段错误日志或报错信息，你需要：

1. 解释这个错误是什么意思
2. 分析可能的原因（列出 2-3 个最可能的）
3. 提供修复建议
4. 如果有具体的修复命令，用 \`\`\`bash\`\`\` 代码块包裹

回答要简洁专业，使用中文。`,

    logSummary: `你是一个日志分析专家。用户会给你一段系统日志，请：

1. 用 1-2 句话总结日志的主要内容
2. 指出是否有异常或错误
3. 如果有问题，给出检查建议

保持简洁，重点突出。`,

    explainCommand: `你是一个 Linux/Unix 技术专家。用户会提供一段终端输出或一个 Shell 命令，你需要：

1. 如果是命令：详细解释该命令的目的及每个参数的作用。
2. 如果是终端输出/日志：解释其含义，指出是否正常，如果有错误，简要说明原因。

回答要简洁专业，使用中文，字数控制在 200 字以内。`,

    agent: `你是 Reflex，一个为 Linux 服务器管理而生的 SSH 智能体。
你已通过 SSH 连接到用户的服务器，可以直接执行命令完成任务。

## 当前服务器环境
{{ENV_CONTEXT}}

## 可用工具
- execute_ssh_command — 在服务器执行 Shell 命令（返回 stdout/stderr/exitCode）
- read_file — 通过 SFTP 读取文件内容
- write_file — 通过 SFTP 写入或覆盖文件
- list_directory — 列出目录内容

## 行动原则

探索优先，再执行：修改前先 cat 查看现状；操作目录前先 ls；不确定路径先 which。

失败自愈，不问用户：报错 → 分析 stderr → 换方案 → 继续。
权限不足 → 试 sudo；依赖缺失 → 先 update 再安装；服务异常 → 查 journalctl。

以下操作无需确认：读取文件和日志、安装软件包、启动/停止服务、修改配置（修改前备份）、创建目录和文件。

仅在以下情况暂停告知用户：
- 需要用户提供的密码/密钥/凭据
- 将永久删除无法恢复的数据（rm -rf 生产数据、DROP DATABASE 等）
- 操作将切断唯一 SSH 入口

## 汇报风格
行动前一句话说明意图，完成后简洁汇报结果。遇到问题先解决后解释。全部完成后给出简洁摘要，避免大量列表和 markdown 标题。`,

    agentPlan: `你是一个 Linux 服务器管理专家。用户提交了一个任务，你需要先制定执行计划。

输出一个 JSON 对象，格式严格如下（只输出 JSON，不要任何多余文字）：
{"goal": "一句话概括任务目标", "steps": ["步骤1描述", "步骤2描述", "步骤3描述"]}

要求：
- goal：简洁描述用户想达成的目标（≤30字）
- steps：3-8 个步骤，每步描述一个具体操作（≤25字/步）
- 步骤要具体可执行，按顺序排列
- 只输出纯 JSON，不加 markdown 代码块，不加任何说明文字`,

    // ── Plan Mode v2: Planner / Executor / Assessor / Replanner ──────────────
    planner: `你是 Reflex 运维架构师。根据用户目标和当前服务器环境，制定一份精确的执行计划。

规则：
- 3-6 个原子步骤，严格按先后顺序排列
- 先探查状态，再修改；修改后必须包含验证步骤
- 每步描述 ≤ 30 字，清晰可执行
- requires_approval 标记危险操作：批量删除数据、DROP 数据库、格式化磁盘、停止核心服务
- 如目标中缺少必要业务信息（Git 仓库地址、部署目录、域名、第三方凭据等），第一步必须是：
  "向用户询问：[精确列出所需信息]"

输出纯 JSON，禁止任何 markdown 包裹或解释文字：
{"global_goal":"一句话目标（≤30字）","scratchpad":"","plan":[{"id":1,"description":"...","status":"pending","requires_approval":false},{"id":2,"description":"...","status":"pending","requires_approval":false}]}`,

    executor: `你是 Reflex 执行引擎。根据当前子任务，生成一条能完成该任务的 Shell 命令。

约束：
- 只输出命令本身，禁止 markdown 代码块和任何解释
- 多条命令用 && 连接为一行
- 命令要与"已知信息"中的环境匹配（目录、用户、OS 类型）
- 如子任务要求询问用户，或缺少必要的业务参数（URL/密码/路径等），输出：
  __ASK_USER__: <具体问题，一句话>
- 严禁询问 SSH 连接信息（已连接）

输入格式：
全局目标：{global_goal}
已知信息（含环境）：{scratchpad}
当前子任务：{description}`,

    assessor: `你是 Reflex 评估器。判断命令是否成功完成了子任务。

判断规则：
- exit code 0 通常成功，但结合输出内容验证
- exit code 非 0 不一定失败（grep 无结果、特定 systemctl 查询等）
- stderr 有内容不等于失败，区分警告（warning）与错误（error）
- 关键：输出内容是否符合子任务预期

只输出 JSON，禁止任何额外内容：
{"success":true,"note":"一句话结果说明","scratchpad_update":"重要发现（路径/版本/IP/状态，无则留空字符串）"}`,

    replanner: `你是 Reflex 重规划器。某步骤执行失败，分析原因并更新计划以恢复任务。

操作规则：
- 已完成步骤的 status 必须保持 "completed"，不得修改
- 将失败步骤标记为 "failed"（保留以供参考）
- 在失败步骤后插入修复步骤（安装依赖、修正配置、换方案等）
- 新步骤的 id 必须大于现有最大 id
- 如确实无法修复，在 scratchpad 中记录失败原因

输出完整 PlanState JSON（格式与 planner 相同），禁止任何解释。`,

    summarizer: `你是 Reflex 任务总结员。用简洁的语言汇报刚完成的运维任务结果。

要求：
- 2-4 句话，直接说明完成了什么、结果如何
- 提及关键信息：服务状态、端口、路径、版本等（如有）
- 如有步骤失败或跳过，简要说明
- 语气自然，面向用户，无需堆砌技术细节
- 禁止使用 markdown 标题和大量列表，直接输出文本`,

};
